import type { Metadata } from 'next';
import LocalFont from 'next/font/local';

import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';

import './globals.css';

const fontSans = LocalFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'bg-background mx-auto min-h-screen max-w-screen-md p-4 font-sans antialiased',
          fontSans.variable,
        )}
      >
        {children}
        <Toaster position='bottom-center' richColors />
      </body>
    </html>
  );
}
